### ISSUE TITLE
META-DES different results if running only its integration test vs running all tests

### ISSUE THREAD

**Issue by luizgh** [Menelau/DESlib#59]
META-DES different results if running only this test vs running all tests: 0.9121212121212121, 0.8909090909090909

**Comment by Menelau** [comment]
Fixed in commit 673d535

This problem was due to the method used to check if the meta-classifier was already trained. 

When running all tests together, the second time the META-DES was called (by a different test script) the previous verification routine was considering that the meta-classifier was already trained when in fact it was not and was skipping the meta-training routine. That was the reason the result dropped from 0.912 to 0.89 (the meta-classifier was not being fitted to the new data).
