### ISSUE TITLE
Investigate issues with DFP mask in batch processing

### ISSUE THREAD

**Issue by luizgh** [Menelau/DESlib#61]
DFP mask in batch processing is different than previous results. Investigate

**Comment by Menelau** [comment]
The difference in performance is not due to the DFP mask, it is caused by the changes in the majority voting function. Since in this version the majority voting is receiving a masked array as input votes (where the votes of incompetent classifiers are masked) it was changed from the masked version (scipy.mstats.mode). This function handles an equal number of votes differently than the scipy.stats.mode which was used in the previous version:

scipy.mstats.mode:
Masked array = [1, --, --, 0, --, --, --, --, --, --] - > class = 1 (it always returns the first value. In this case the prediction of the first selected base classifier will be return)

scipy.stats.mode:
Array = [1, 0] -> scipy.stats.mode -> class 0 (This function sort the input array first when using the np.unique function. So, it always returns the lowest value among the voted class labels)

That is why DES-P and KNORA-E methods are giving slightly different results in the new version (This confusion happens with sample index 173 having one vote for each class). We cannot say the new implementation is giving wrong results. One thing that could be done is having a tie break mechanism when two classes have the same number of votes by choosing the one with highest a priori probability instead of selecting either the prediction of the first base classifier or the class label with lowest value. However, since that is not a change that will significantly impact the system we can leave for the next release since we need to release the new version containing label encoder and batch processing soon.
