### ISSUE TITLE
Create check_estimator tests

### ISSUE THREAD

**Issue by luizgh** [Menelau/DESlib#84]
Setup tests for all methods using sklearn.utils.estimator_checks.check_estimator. Tests should be setup on the test file for each class.

**Comment by Menelau** [comment]
@luizgh Great! About these problems with META-DES I believe the problem is due to the number of examples used in the test routine (the size of the training dataset is lower than the number of neighbors). That catches a very specific problem in this code.

About the static combination methods, we need to change them to the same format as the other DS methods (fit the ensemble inside if not informed), so that all classes in the library are consistent and compatible with sklearn standards. In this case, we also need to prepare estimator tests for these classes.

**Comment by luizgh** [comment]
I updated the check_estimator to run on the subclasses of Probabilistic. It worked for most of them, but failed for "MinimumDifference" in a corner case where all training points are from only one of the classes. I think this needs to be handled in the code, so I will create a new issue for it. I will also create a new issue to investigate the META-DES problem, and update issue #86 to remember to add the new "fit" behavior on the static classes.

**Comment by luizgh** [comment]
created issues #91 and #92
